spring.application.name=apiJogos
spring.datasource.url=jdbc:mysql://localhost:3306/apiJogosBD?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://[project-id-supabase].supabase.co/auth/v1


spring.datasource.username=usuario
spring.datasource.password=senha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

server.port=35555

# teste no postman:
# post: https://[project-id-supabase].supabase.co/auth/v1/token?grant_type=password
# headers:
# apikey: [legacy anon public]
# content-type: aplication/json
